### ISSUE TITLE
버그x but 작은 제안사항

### ISSUE THREAD

**Issue by yellyB** [Edunga1/canvas-floating-alphabet#1]
개발자님 알파벳 조각들이 날아갈때 속이 시원하고 넘 재밌습니다.
근데 더 속시원하게 마구마구 흩뜨리고 싶은데 꾹 누르면 리셋되는 기능때문에 자꾸 원상태로 돌아가버리는데요.
혹시 드래그 기능을 넣어서 드래그로도 날아가는 기능을 넣어주심 안되나요?
귀찮으시거나 이 기능이 맘에 안드신다면... 제가 한번 따로 수정을 해봐도 될지 조심스럽게 문의를 드려봅니다...🙇‍♀️🙇‍♀️

**Comment by Edunga1** [comment]
어우, 기여해 주시면 너무 감사합니다!
